services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: mydevcontainer
    privileged: true
    volumes:
      # mount your repository folder in here
      - ~/code/:/root/code/
      # mount gitconfig to use your own github user
      - ~/.gitconfig:/root/.gitconfig